frontend_group:
    ng_site_api:
        site_api_is_primary_content_view: true
        fallback_to_secondary_content_view: false
        fail_on_missing_field: "%kernel.debug%"
        render_missing_field_info: false
        named_objects: []
        named_queries: []
    ng_content_view:
        full:
            ng_category:
                template: "@ibexadesign/content/full/ng_category.html.twig"
                controller: ngsite.controller.check_redirect
                queries:
                    subtree:
                        query_type: "SiteAPI:Location/Subtree"
                        max_per_page: "@=fieldValue('page_limit').value > 0 ? fieldValue('page_limit').value : 12"
                        page: "@=queryParam('page', 1)"
                        parameters:
                            content_type: "@=split(fieldValue('children_class_filter_include').text)"
                            relative_depth: "@=fieldValue('fetch_subtree').bool ? null : 1"
                            sort: "@=location"
                match:
                    Identifier\ContentType: ng_category
            ng_feedback_form:
                template: "@ibexadesign/content/full/ng_feedback_form.html.twig"
                controller: netgen_information_collection.controller.collect_information
                match:
                    Identifier\ContentType: ng_feedback_form
            ng_landing_page:
                template: "@ibexadesign/content/full/ng_landing_page.html.twig"
                controller: ngsite.controller.check_redirect
                match:
                    Identifier\ContentType: ng_landing_page
            common:
                template: "@ibexadesign/content/full/{content_type}.html.twig"
                match:
                    Identifier\ContentType:
                        - ng_article
                        - ng_audio
                        - ng_blog_post
                        - ng_frontpage
                        - ng_gallery
                        - ng_htmlbox
                        - ng_news
                        - ng_recipe
                        - ng_topic
                        - ng_video
            match_all:
                redirect:
                    target: '@=namedLocation("homepage")'
                    permanent: true
                    keep_request_method: '%kernel.debug%'
                match: ~
        line:
            common:
                template: "@ibexadesign/content/line/{content_type}.html.twig"
                match:
                    Identifier\ContentType:
                        - file
                        - ng_article
                        - ng_audio
                        - ng_banner
                        - ng_blog_post
                        - ng_category
                        - ng_feedback_form
                        - ng_gallery
                        - ng_landing_page
                        - ng_news
                        - ng_recipe
                        - ng_video
            match_all:
                template: "@ibexadesign/content/line.html.twig"
                match: ~
        listitem:
            common:
                template: "@ibexadesign/content/listitem/{content_type}.html.twig"
                params:
                    with_intro: false
                match:
                    Identifier\ContentType:
                        - file
                        - ng_article
                        - ng_audio
                        - ng_banner
                        - ng_blog_post
                        - ng_gallery
                        - ng_news
                        - ng_recipe
                        - ng_video
            match_all:
                template: "@ibexadesign/content/listitem.html.twig"
                params:
                    with_intro: false
                match: ~
        listitem_with_intro:
            common:
                extends: listitem/common
                params:
                    with_intro: true
            match_all:
                template: "@ibexadesign/content/listitem.html.twig"
                params:
                    with_intro: true
                match: ~
        standard:
            common:
                template: "@ibexadesign/content/standard/{content_type}.html.twig"
                params:
                    with_intro: false
                match:
                    Identifier\ContentType:
                        - file
                        - image
                        - ng_article
                        - ng_audio
                        - ng_banner
                        - ng_blog_post
                        - ng_category
                        - ng_feedback_form
                        - ng_frontpage
                        - ng_gallery
                        - ng_htmlbox
                        - ng_landing_page
                        - ng_news
                        - ng_recipe
                        - ng_video
            match_all:
                template: "@ibexadesign/content/standard.html.twig"
                params:
                    with_intro: false
                match: ~
        standard_with_intro:
            common:
                extends: standard/common
                params:
                    with_intro: true
            match_all:
                template: "@ibexadesign/content/standard.html.twig"
                params:
                    with_intro: true
                match: ~
        mini:
            common:
                template: "@ibexadesign/content/mini/{content_type}.html.twig"
                match:
                    Identifier\ContentType:
                        - file
                        - ng_article
                        - ng_audio
                        - ng_banner
                        - ng_blog_post
                        - ng_gallery
                        - ng_news
                        - ng_recipe
                        - ng_video
            match_all:
                template: "@ibexadesign/content/mini.html.twig"
                match: ~
        overlay:
            common:
                template: "@ibexadesign/content/overlay/{content_type}.html.twig"
                match:
                    Identifier\ContentType:
                        - ng_article
                        - ng_banner
                        - ng_blog_post
                        - ng_gallery
                        - ng_news
                        - ng_recipe
                        - ng_video
            match_all:
                template: "@ibexadesign/content/overlay.html.twig"
                match: ~
        slide:
            common:
                template: "@ibexadesign/content/slide/{content_type}.html.twig"
                match:
                    Identifier\ContentType:
                        - image
                        - ng_article
                        - ng_banner
                        - ng_blog_post
                        - ng_news
                        - ng_video
            match_all:
                template: "@ibexadesign/content/slide.html.twig"
                match: ~
        gallery_thumb:
            common:
                template: "@ibexadesign/content/gallery_thumb/{content_type}.html.twig"
                match:
                    Identifier\ContentType:
                        - image
                        - ng_article
                        - ng_banner
                        - ng_blog_post
                        - ng_news
                        - ng_video
            match_all:
                template: "@ibexadesign/content/gallery_thumb.html.twig"
                match: ~
        gallery_grid:
            common:
                template: "@ibexadesign/content/gallery_grid/{content_type}.html.twig"
                match:
                    Identifier\ContentType:
                        - image
                        - ng_article
                        - ng_banner
                        - ng_blog_post
                        - ng_news
                        - ng_video
            match_all:
                template: "@ibexadesign/content/gallery_grid.html.twig"
                match: ~
        embed:
            image:
                template: "@ibexadesign/content/embed/image.html.twig"
                controller: ngsite.controller.embed_view.image
                match:
                    Identifier\ContentType: image
            common:
                template: "@ibexadesign/content/embed/{content_type}.html.twig"
                match:
                    Identifier\ContentType:
                        - file
                        - image
                        - ng_article
                        - ng_audio
                        - ng_banner
                        - ng_blog_post
                        - ng_category
                        - ng_feedback_form
                        - ng_frontpage
                        - ng_gallery
                        - ng_htmlbox
                        - ng_landing_page
                        - ng_news
                        - ng_shortcut
                        - ng_video
            match_all:
                template: "@ibexadesign/content/embed.html.twig"
                match: ~
        search:
            match_all:
                template: "@ibexadesign/content/search.html.twig"
                match: ~

default:
    ng_content_view:
        ngcb_preview:
            common:
                template: "@ibexadesign/content/ngcb_preview/{content_type}.html.twig"
                match:
                    Identifier\ContentType:
                        - image
                        - ng_article
                        - ng_audio
                        - ng_banner
                        - ng_blog_post
                        - ng_gallery
                        - ng_news
                        - ng_video
                        - ng_recipe
