ez_core_extra:
    system:
        default:
            twig_globals:
                date_format: 'd MMM y'
                datetime_format: 'd MMM y, H:mm'
        bold_ger:
            twig_globals:
                date_format: 'd. MMMM y'
                datetime_format: 'd. MMMM y, H:mm'
