netgen_open_graph:
    system:
        frontend_group:
            global_handlers:
                - { handler: ngsite/site_name, tag: "og:site_name" }
                - { handler: literal/canonical_url, tag: "og:url" }
            content_type_handlers:
                ng_frontpage:
                    - { handler: literal/text, tag: "og:type", params: [website] }
                    - { handler: ngsite/site_name, tag: "og:title" }
                    - { handler: ngsite/site_name, tag: "og:description" }
                    - { handler: ngsite/site_image, tag: "og:image" }
                ng_landing_page:
                    - { handler: literal/text, tag: "og:type", params: [website] }
                    - { handler: field_type/ezstring, tag: "og:title", params: [title] }
                    - { handler: ngsite/site_image, tag: "og:image" }
                ng_category:
                    - { handler: literal/text, tag: "og:type", params: [website] }
                    - { handler: field_type/ezstring, tag: "og:title", params: [title] }
                    - { handler: field_type/ezrichtext, tag: "og:description", params: [full_intro] }
                ng_article:
                    - { handler: literal/text, tag: "og:type", params: [article] }
                    - { handler: field_type/ezstring, tag: "og:title", params: [title] }
                    - { handler: field_type/ezrichtext, tag: "og:description", params: [full_intro] }
                    - { handler: field_type/ezimage, tag: "og:image", params: [image, i1320] }
                ng_news:
                    - { handler: literal/text, tag: "og:type", params: [article] }
                    - { handler: field_type/ezstring, tag: "og:title", params: [title] }
                    - { handler: field_type/ezrichtext, tag: "og:description", params: [full_intro] }
                    - { handler: field_type/ezimage, tag: "og:image", params: [image, i1320] }
                ng_blog_post:
                    - { handler: literal/text, tag: "og:type", params: [article] }
                    - { handler: field_type/ezstring, tag: "og:title", params: [title] }
                    - { handler: field_type/ezrichtext, tag: "og:description", params: [full_intro] }
                    - { handler: field_type/ezimage, tag: "og:image", params: [image, i1320] }
                ng_contact_form:
                    - { handler: literal/text, tag: "og:type", params: [article] }
                    - { handler: field_type/ezstring, tag: "og:title", params: [title] }
                    - { handler: field_type/ezrichtext, tag: "og:description", params: [full_intro] }
                    - { handler: ngsite/site_image, tag: "og:image" }
