admin_index:
    path: /admin
    controller: 'Symfony\Bundle\FrameworkBundle\Controller\RedirectController::redirectAction'
    methods: [GET]
    defaults:
        route: admin_dashboard_index
        permanent: true

admin_dashboard_index:
    path: /admin/dashboard
    controller: App\Controller\Admin\Dashboard\Index
    methods: [GET]
