admin_index:
    path: /backoffice
    controller: 'Symfony\Bundle\FrameworkBundle\Controller\RedirectController::redirectAction'
    methods: [GET]
    defaults:
        route: backoffice_dashboard_index
        permanent: true

backoffice_dashboard_index:
    path: /backoffice/dashboard
    controller: App\Controller\Backoffice\Dashboard\Index
    methods: [GET]
