parameters:
    ngsite.default.search.content_types:
        - ng_article
        - ng_audio
        - ng_blog_post
        - ng_category
        - ng_contact_form
        - ng_job_position
        - ng_landing_page
        - ng_news
        - ng_video
        - file

    ngsite.default.lazy_loading.enabled: true

    ngsite.default.token_validity.email_change: 900

    app.testing.site_domain: '%env(TEST_DOMAIN)%'
