parameters:
    ngsite.default.search.content_types:
        - ng_article
        - ng_audio
        - ng_blog_post
        - ng_category
        - ng_contact_form
        - ng_job_position
        - ng_landing_page
        - ng_news
        - ng_video
        - file

    ngsite.default.lazy_loading.enabled: true

    ngsite.default.token_validity.email_change: 900

    app.testing.site_domain: '%env(TEST_DOMAIN)%'

    ngsite.default.email_change.token_validity_time_minutes: 15

    netgen_user_impersonation.default.content_type_identifier.user_groups: ['user_group']
    netgen_user_impersonation.default.content_type_identifier.users: ['user']
    netgen_user_impersonation.default.users.root_location_ids: [5]
    netgen_user_impersonation.default.users.name_search_fields: ['first_name', 'last_name']
    netgen_user_impersonation.admin.siteaccess_name: '%ngsite.admin_siteaccess_name%'
    netgen_user_impersonation.default.admin.pagelayout: 'backoffice/user_impersonation/layout.html.twig'
    netgen_user_impersonation.peak_eng.impersonate.default_target.route: 'backoffice_dashboard_index'
