# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    # todo key is optional
    app.mailer_lite.api_key: 'dummy'
    app.layouts.block.plugin.features_component_grid.columns:
        2: '2 columns'
        3: '3 columns'
        4: '4 columns'
    netgen_information_collection.default.form.use_csrf: false

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        bind:
            # todo this should be optional
            $newsletterSenderEmail: 'support+noreply@netgen.io'
            $newsletterRecipientEmail: 'support+noreply@netgen.io'

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../../src/'
        exclude:
            - '../../src/DependencyInjection/'
            - '../../src/Entity/'
            - '../../src/Kernel.php'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    netgen_information_collection.handler:
        class: App\InformationCollection\Handler\Handler
        public: true
        arguments:
            - "@form.factory"
            - "@ibexa.api.service.content_type"
            - "@event_dispatcher"

    App\Controller\InfoCollectionController:
        class: App\Controller\InfoCollectionController
        arguments:
            $handler: '@netgen_information_collection.handler'
            $captchaService: '@netgen_information_collection.captcha.service'
            $contentRenderer: '@netgen.ibexa_site_api.twig.content_renderer'

    App\Controller\ModalViewController:
        class: App\Controller\ModalViewController
        arguments:
            - '@netgen.ibexa_site_api.twig.content_renderer'

    netgen_information_collection.mailer:
        class: Netgen\InformationCollection\Core\Mailer\SymfonyMailerBasedMailer
        arguments:
            - '@mailer.mailer'

    App\InformationCollection\Action\EmailAction:
        arguments:
            - '@mailer.mailer'
            - '@netgen_information_collection.factory.email_data'
        tags:
            - { name: netgen_information_collection.action }

    App\InformationCollection\Action\NewsletterAction:
        arguments:
            - '@mailer.mailer'
        tags:
            - { name: netgen_information_collection.action }

    Netgen\Bundle\InformationCollectionBundle\Templating\Twig\Extensions\CaptchaExtension:
        tags:
            - { name: twig.extension }

    Netgen\Bundle\InformationCollectionBundle\Templating\Twig\Extensions\CaptchaRuntime:
        arguments:
            - '@netgen_information_collection.captcha.service'
        tags:
            - { name: twig.runtime }

    MailerLiteApi\MailerLite:
        arguments:
            - '%app.mailer_lite.api_key%'
        public: false

