backoffice_bookmarks_index:
    path: /bookmarks
    controller: App\Controller\Backoffice\Bookmarks\Index
    methods: [GET]

backoffice_bookmarks_delete:
    path: /bookmarks/delete/{id}
    controller: App\Controller\Backoffice\Bookmarks\Delete
    methods: [GET, POST]
    requirements:
        id: \d+
