backoffice_index:
    path: /
    controller: 'Symfony\Bundle\FrameworkBundle\Controller\RedirectController::redirectAction'
    methods: [GET]
    defaults:
        route: backoffice_dashboard_index
        permanent: true

backoffice_dashboard_index:
    path: /dashboard
    controller: App\Controller\Backoffice\Dashboard\Index
    methods: [GET]

backoffice_bookmarks_index:
    path: /bookmarks
    controller: App\Controller\Backoffice\Bookmarks\Index
    methods: [GET]

backoffice_bookmarks_delete:
    path: /bookmarks/delete/{id}
    controller: App\Controller\Backoffice\Bookmarks\Delete
    methods: [GET, POST]
    requirements:
        id: \d+
