backoffice_index:
    path: /
    controller: 'Symfony\Bundle\FrameworkBundle\Controller\RedirectController::redirectAction'
    methods: [GET]
    defaults:
        route: backoffice_dashboard_index
        permanent: true

backoffice_dashboard_index:
    path: /dashboard
    controller: App\Backoffice\Controller\Dashboard\Index
    methods: [GET]
